version: "3.9"
services:
  traefik:
    image: traefik:v3.1
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"
      - "8081:8080" # traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-profile:
    build: ./services/user-profile
    environment:
      PORT: 8080
      DATABASE_URL: postgres://user:pass@postgres:5432/userdb
      LOG_LEVEL: info
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user-profile.rule=PathPrefix(`/`)"
      - "traefik.http.services.user-profile.loadbalancer.server.port=8080"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  pgdata:

